"""add agent_name to chats

Revision ID: 2e6ee2cce750
Revises: 1607bee21d74
Create Date: 2026-05-24 14:17:38.766674

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2e6ee2cce750'
down_revision: Union[str, Sequence[str], None] = '1607bee21d74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    "chats",
    sa.Column(
        "agent_name",
        sa.String(length=50),
        nullable=False,
        server_default="assistant",
    ),
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'agent_name')
    # ### end Alembic commands ###
