"""add users table

Revision ID: 3d28b1670cbd
Revises: ff4668dd16f9
Create Date: 2026-05-21 13:23:16.794860

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '3d28b1670cbd'
down_revision: Union[str, Sequence[str], None] = 'ff4668dd16f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
