"""adjust chat schema

Revision ID: 42898dc0e993
Revises: e6c775dfd252
Create Date: 2026-05-23 11:21:33.702096

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '42898dc0e993'
down_revision: Union[str, Sequence[str], None] = 'e6c775dfd252'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
