"""add chunk embeddings

Revision ID: 5bdef629d629
Revises: e20a94017dae
Create Date: 2026-06-21 14:03:10.371076

"""
from typing import Sequence, Union

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5bdef629d629'
down_revision: Union[str, Sequence[str], None] = 'e20a94017dae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    embedding_status = postgresql.ENUM(
            "pending",
            "processing",
            "completed",
            "failed",
            name="embeddingstatus",
        )

    embedding_status.create(op.get_bind(), checkfirst=True)
    op.create_table('chunk_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_id')
    )
    op.execute("""
    ALTER TABLE documents
    ALTER COLUMN embedding_status DROP DEFAULT
    """)
    op.alter_column(
        "documents",
        "embedding_status",
        existing_type=sa.VARCHAR(length=20),
        type_=embedding_status,
        postgresql_using="embedding_status::embeddingstatus",
        existing_nullable=False,
    )

    op.execute(
        "ALTER TABLE documents ALTER COLUMN embedding_status SET DEFAULT 'pending'"
    )
    op.alter_column('workflow_steps', 'depends_on',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflow_steps', 'depends_on',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('documents', 'embedding_status',
               existing_type=sa.Enum('pending', 'processing', 'completed', 'failed', name='embeddingstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.drop_table('chunk_embeddings')
    # ### end Alembic commands ###
