"""change_embedding_dimension

Revision ID: 678115a0bc6f
Revises: 5bdef629d629
Create Date: 2026-06-22 18:46:21.031332

"""
from typing import Sequence, Union

import pgvector.sqlalchemy

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '678115a0bc6f'
down_revision: Union[str, Sequence[str], None] = '5bdef629d629'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chunk_embeddings', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chunk_embeddings', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=False)
    # ### end Alembic commands ###
