"""add workflow runs and step runs

Revision ID: 75ee3bb85ff1
Revises: 7edec73e6d5c
Create Date: 2026-05-25 11:17:26.756805

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '75ee3bb85ff1'
down_revision: Union[str, Sequence[str], None] = '7edec73e6d5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
