"""DAG execution

Revision ID: 91cc967ec6f2
Revises: 149bf5603048
Create Date: 2026-05-28 14:35:50.343440

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '91cc967ec6f2'
down_revision: Union[str, Sequence[str], None] = '149bf5603048'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_steps', sa.Column('depends_on', sa.JSON(), nullable=True))
    op.add_column('workflow_steps', sa.Column('condition', sa.Text(), nullable=True))
    op.create_index('ix_workflow_steps_workflow_order', 'workflow_steps', ['workflow_id', 'step_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workflow_steps_workflow_order', table_name='workflow_steps')
    op.drop_column('workflow_steps', 'condition')
    op.drop_column('workflow_steps', 'depends_on')
    # ### end Alembic commands ###
