"""add_metrics_for_document

Revision ID: b2f0618f384e
Revises: ca2bd54e4890
Create Date: 2026-06-20 02:02:11.331160

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b2f0618f384e'
down_revision: Union[str, Sequence[str], None] = 'ca2bd54e4890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('start_offset', sa.Integer(), nullable=True))
    op.add_column('document_chunks', sa.Column('end_offset', sa.Integer(), nullable=True))
    op.add_column('document_chunks', sa.Column('embedding_id', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('processing_finished_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('processing_duration_ms', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('embedding_status', sa.String(length=20), nullable=False, server_default='PENDING'))
    op.alter_column('documents', 'filepath',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1024),
               existing_nullable=False)
    op.alter_column('documents', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('uploaded', 'processing', 'indexed', 'failed', name='documentstatus', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflow_steps', 'depends_on',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('documents', 'status',
               existing_type=sa.Enum('uploaded', 'processing', 'indexed', 'failed', name='documentstatus', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('documents', 'filepath',
               existing_type=sa.String(length=1024),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('documents', 'embedding_status')
    op.drop_column('documents', 'processing_duration_ms')
    op.drop_column('documents', 'processing_finished_at')
    op.drop_column('documents', 'processing_started_at')
    op.drop_column('document_chunks', 'embedding_id')
    op.drop_column('document_chunks', 'end_offset')
    op.drop_column('document_chunks', 'start_offset')
    # ### end Alembic commands ###
