"""adjust message schema

Revision ID: e6c775dfd252
Revises: 7ceadf3090e5
Create Date: 2026-05-23 10:37:18.507325

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'e6c775dfd252'
down_revision: Union[str, Sequence[str], None] = '7ceadf3090e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
